### ISSUE TITLE
Entities unavailable

### ISSUE THREAD

**Issue by jon-moreira** [tomasbedrich/home-assistant-skydance#12]
After last update of home assistant all my entities of sky scanner are unavailable 

![image](https://github.com/user-attachments/assets/83f51fe3-e6bc-4380-a3e5-c650c4223e4e)

![image](https://github.com/user-attachments/assets/b06a8f83-5260-44ce-9ddd-6b7b14ddeb9d)

This error originated from a custom integration.

Logger: custom_components.skydance.light
Source: helpers/update_coordinator.py:354
integration: Skydance (documentation, issues)
First occurred: 11:19:47 (2 occurrences)
Last logged: 11:28:34

Unexpected error fetching skydance data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/skydance/light.py", line 92, in async_update
    zone_info.type,
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/skydance/protocol.py", line 427, in type
    return ZoneType(self.body[12])
                    ~~~~~~~~~^^^^
IndexError: index out of range

———

Logger: homeassistant
Source: runner.py:147
First occurred: 11:43:41 (1 occurrences)
Last logged: 11:43:41

Error doing job: Task was destroyed but it is pending! (<Task pending name='Task-2800' coro=<async_setup_entry() running at /config/custom_components/skydance/light.py:68> wait_for=<Future pending cb=[Task.task_wakeup()]>>)

———

This error originated from a custom integration.

Logger: custom_components.skydance.config_flow
Source: custom_components/skydance/config_flow.py:67
integration: Skydance (documentation, issues)
First occurred: 11:41:51 (2 occurrences)
Last logged: 11:41:59

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/skydance/config_flow.py", line 67, in async_step_user
    self._abort_if_unique_id_configured()
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2434, in _abort_if_unique_id_configured
    raise data_entry_flow.AbortFlow(error)
homeassistant.data_entry_flow.AbortFlow: Flow aborted: already_configured



**Home assistant info**
Core: 2024.10.4
Supervisor: 2024.10.3
Operating System: 13.2
Frontend: 20241002.4

**Comment by tomasbedrich** [comment]
Hello, I am sorry but as I don't own Skydance relays anymore, I am not able to debug the integration.

One thing which comes to my mind – did you notice any deprecation warnings raised for Skydance integration **before** the update?
